<?php 
$this->placeholder('sidebar')
     ->setPrefix('<ul class="sidebar">')
     ->setPostfix('</ul>');
$this->headTitle('Mobile Device Demo')
     ->setSeparator(' - ');
$this->headLink()->prependStylesheet('/css/960.css')
                 ->prependStylesheet('/css/text.css')
                 ->prependStylesheet('/css/reset.css');

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
<?php 
    echo $this->headTitle();
    echo $this->headLink();
    echo $this->headScript();
?>
</head>
<body>
<?php echo $this->placeholder('sidebar') ?>
<?php echo $this->layout()->content; ?>
</body>
</html>
