<?php 
$this->placeholder('sidebar')
     ->setPrefix('<ul class="sidebar">')
     ->setPostfix('</ul>');
$this->headTitle('Mobile Device Demo')
     ->setSeparator(' - ');
$this->headLink()->prependStylesheet('/css/mobile-demo-desktop.css')
                 ->prependStylesheet('/css/960.css')
                 ->prependStylesheet('/css/text.css')
                 ->prependStylesheet('/css/reset.css');

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
<?php 
    echo $this->headTitle();
    echo $this->headLink();
    echo $this->headScript();
?>
</head>
<body>
<div class="container_12 application">
    <div class="grid_12 header">
        <h1>ZF Mobile Demo</h1>
    </div>
    <div class="clear"></div>

    <div class="grid_12 spacer"></div>
    <div class="clear"></div>

    <div class="grid_10 content">
        <?php echo $this->layout()->content; ?>
    </div>
    <div class="grid_2 sidebar">
        <?php echo $this->placeholder('sidebar') ?>
    </div>
    <div class="clear"></div>

    <div class="grid_12 spacer"></div>
    <div class="clear"></div>

    <div class="grid_6 footer1">
        &copy; 2010 Zend Technologies
    </div>
    <div class="grid_6 footer2">
        <a href="http://framework.zend.com/manual/en/zend.http.user-agent.html">Zend_Http_UserAgent docs</a>
    </div>
    <div class="clear"></div>

    <div class="grid_12 spacer"></div>
    <div class="clear"></div>
</div>
</body>
</html>
