<div id="welcome">
    <h1>Mobile Device Demonstration Application</span></h1>

    <p>
        This application is intended to show off some of the features of 
        <a href="http://framework.zend.com/">Zend Framework 1.11's</a> mobile
        capabilities.
    </p>
</div>

<?php $this->placeholder('sidebar')->captureStart() ?>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'mobile',
            'action'     => 'details',
        ), 'default') ?>">List of mobile capabilities</a></li>

        <li><a href="<?php echo $this->url(array(
            'controller' => 'mobile',
            'action'     => 'dojo',
        ), 'default') ?>">dojox.mobile</a></li>
<?php $this->placeholder('sidebar')->captureEnd() ?>
