<h2>Device Capabilities</h2>
<dl>
<?php foreach ($this->device->getAllFeatures() as $feature => $value): ?>
    <dt><?php echo $this->escape($feature) ?></dt>
    <dd><?php 
    if (is_string($value)) {
        echo $this->escape($value);
    } else {
        echo '<pre>' . var_export($value, true) . '</pre>';
    } ?>
    </dd>
<?php endforeach ?>
</dl>

<?php $this->placeholder('sidebar')->captureStart() ?>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'index',
            'action'     => 'index',
        ), 'default') ?>">Home</a></li>

        <li><a href="<?php echo $this->url(array(
            'controller' => 'mobile',
            'action'     => 'image',
        ), 'default') ?>">Scaled image</a></li>
<?php $this->placeholder('sidebar')->captureEnd() ?>
