<h2>Scaled Image</h2>

<p>
<?php 
    if ($this->userAgent()->getBrowserType() != 'mobile') {
        // Display at 75% width on normal pages
        echo $this->tinySrc('/images/seascape.jpg', array('width' => 'x75'));
    } else {
        // Full supported width on mobile devices
        echo $this->tinySrc('/images/seascape.jpg');
    }
?>
</p>

<?php $this->placeholder('sidebar')->captureStart() ?>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'index',
            'action'     => 'index',
        ), 'default') ?>">Home</a></li>

        <li><a href="<?php echo $this->url(array(
            'controller' => 'mobile',
            'action'     => 'my-device',
        ), 'default') ?>">My Device</a></li>

        <li><a href="<?php echo $this->url(array(
            'controller' => 'mobile',
            'action'     => 'details',
        ), 'default') ?>">List of mobile capabilities</a></li>
<?php $this->placeholder('sidebar')->captureEnd() ?>
